### ISSUE TITLE
Dont Start 

### ISSUE THREAD

**Issue by Chalerios** [jrbudda/Vivecraft_110#34]
version 1.7.10 works fine for me ....but 1.10.2 dont start....
the returncode ist follow... thx

[19:11:22] [main/INFO]: Loading tweak class name optifine.OptiFineTweaker
[19:11:22] [main/INFO]: Using primary tweak class name optifine.OptiFineTweaker
[19:11:22] [main/INFO]: Loading tweak class name com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
[19:11:22] [main/INFO]: Calling tweak class optifine.OptiFineTweaker
OptiFineTweaker: acceptOptions
OptiFineTweaker: injectIntoClassLoader
OptiFine ClassTransformer
OptiFine URL: file:/C:/Users/HTC%20Vive/AppData/Roaming/.minecraft/libraries/optifine/OptiFine/1.10.2_HD_U_C2/OptiFine-1.10.2_HD_U_C2.jar
OptiFine ZIP file: C:\Users\HTC Vive\AppData\Roaming\.minecraft\libraries\optifine\OptiFine\1.10.2_HD_U_C2\OptiFine-1.10.2_HD_U_C2.jar
[19:11:22] [main/INFO]: Calling tweak class com.mtbs3d.minecrift.tweaker.MinecriftForgeTweaker
MinecriftForgeTweaker: acceptOptions
MinecriftForgeTweaker: injectIntoClassLoader
Minecrift ClassTransformer
Minecrift URL: file:/C:/Users/HTC%20Vive/AppData/Roaming/.minecraft/libraries/com/mtbs3d/minecrift/1.10.2-Vivecraft-jrbudda-2/minecrift-1.10.2-Vivecraft-jrbudda-2.jar
Minecrift ZIP file: java.util.zip.ZipFile@7d68ef40
OptiFineTweaker: getLaunchArguments
MinecriftForgeTweaker: getLaunchArguments
OptiFineTweaker: getLaunchTarget
[19:11:22] [main/ERROR]: Unable to launch
java.lang.ClassNotFoundException: net.minecraft.client.main.Main
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_101]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_101]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_101]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:131) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	... 6 more
Java HotSpot(TM) 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release

greetings from  germany

**Comment by jrbudda** [comment]
java.lang.ClassNotFoundException: net.minecraft.client.main.Main

it sounds like it failed to download the full minecraft jar file

**Comment by Chalerios** [comment]
ok...try to reinstalla...
thx
