### ISSUE TITLE
Crashes when you bring up a map in your inventory

### ISSUE THREAD

**Issue by ljw1004** [jrbudda/Vivecraft_110#65]
SETUP

Minecraft 1.10
Vivecraft 1.10.2 v6 (it also happened with older versions)
HTC Vive.

REPRO
1. Create a map, place it in your inventory and look at it. Now it shows your area.
2. Using the left touchpad, scroll your "current inventory selector" left (wrapping around) until it gets to the map again.

WHAT I GET:

It crashes whenever I scroll my current inventory selector leftwards onto the map using the left touchpad.

Note: it doesn't crash when I scroll the selector _rightwards_ onto the map.

Here's a typical crash report. It's always at `aef.a < bod.a < bnz.b`.

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 15/09/16 21:26
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
    at aef.a(SourceFile:48)
    at bod.a(ItemRenderer.java:282)
    at bod.a(ItemRenderer.java:262)
    at bod.a(ItemRenderer.java:464)
    at bnz.b(EntityRenderer.java:1080)
    at bnz.b(EntityRenderer.java:1806)
    at bnz.updateCameraAndRender(EntityRenderer.java:1314)
    at bcx.renderSingleView(Minecraft.java:4839)
    at bcx.av(Minecraft.java:1512)
    at bcx.a(Minecraft.java:660)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
    at aef.a(SourceFile:48)
    at bod.a(ItemRenderer.java:282)
    at bod.a(ItemRenderer.java:262)
    at bod.a(ItemRenderer.java:464)
    at bnz.b(EntityRenderer.java:1080)
    at bnz.b(EntityRenderer.java:1806)
    at bnz.updateCameraAndRender(EntityRenderer.java:1314)

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [bnn['ljw1004'/213, l='MpServer', x=303.18, y=64.50, z=258.04]]
    Chunk stats: MultiplayerChunkCache: 1675, 1675
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (342,64,243), Chunk: (at 6,4,3 in 21,15; contains blocks 336,0,240 to 351,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 142927 game time, 142927 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 105 total; [aar['Minecart with Chest'/20, l='MpServer', x=230.50, y=33.06, z=250.50], wi['Pig'/21, l='MpServer', x=236.09, y=62.58, z=248.10], zd['Skeleton'/22, l='MpServer', x=230.50, y=18.00, z=296.50], zg['Spider'/23, l='MpServer', x=227.50, y=18.00, z=301.50], zi['Zombie'/26, l='MpServer', x=241.50, y=63.00, z=236.50], zg['Spider'/27, l='MpServer', x=241.50, y=63.00, z=233.50], wi['Pig'/28, l='MpServer', x=245.55, y=64.00, z=248.51], wi['Pig'/29, l='MpServer', x=255.76, y=78.00, z=316.66], wi['Pig'/30, l='MpServer', x=255.50, y=80.00, z=311.75], zd['Skeleton'/31, l='MpServer', x=258.50, y=63.00, z=221.50], zd['Skeleton'/32, l='MpServer', x=250.96, y=62.00, z=218.51], wa['Bat'/33, l='MpServer', x=265.25, y=26.07, z=231.39], wa['Bat'/34, l='MpServer', x=265.75, y=26.00, z=225.25], wa['Bat'/35, l='MpServer', x=262.39, y=29.05, z=238.40], wn['Squid'/36, l='MpServer', x=267.30, y=59.75, z=264.80], wi['Pig'/37, l='MpServer', x=259.67, y=78.00, z=319.47], wi['Pig'/38, l='MpServer', x=264.52, y=74.00, z=326.99], zd['Skeleton'/56, l='MpServer', x=273.50, y=25.00, z=235.50], wa['Bat'/57, l='MpServer', x=275.46, y=27.51, z=242.52], wi['Pig'/58, l='MpServer', x=281.51, y=64.00, z=280.22], zi['Zombie'/59, l='MpServer', x=281.35, y=77.00, z=307.35], zi['Zombie'/60, l='MpServer', x=282.50, y=58.00, z=334.50], zd['Skeleton'/74, l='MpServer', x=300.50, y=24.00, z=191.50], zi['Zombie'/75, l='MpServer', x=293.50, y=42.00, z=225.50], yk['item.tile.dirt.default'/76, l='MpServer', x=301.08, y=62.00, z=247.21], zd['Skeleton'/77, l='MpServer', x=295.52, y=51.00, z=255.79], wn['Squid'/78, l='MpServer', x=291.81, y=61.22, z=262.26], wn['Squid'/79, l='MpServer', x=294.32, y=60.06, z=269.41], wn['Squid'/80, l='MpServer', x=287.33, y=62.24, z=259.04], wi['Pig'/81, l='MpServer', x=289.41, y=67.00, z=282.55], wa['Bat'/82, l='MpServer', x=301.49, y=45.10, z=325.54], wi['Pig'/90, l='MpServer', x=316.12, y=62.16, z=201.87], wa['Bat'/91, l='MpServer', x=305.50, y=25.10, z=211.43], zd['Skeleton'/92, l='MpServer', x=309.50, y=21.00, z=218.50], wi['Pig'/93, l='MpServer', x=319.47, y=64.00, z=219.79], zd['Skeleton'/94, l='MpServer', x=307.21, y=63.00, z=228.35], zd['Skeleton'/95, l='MpServer', x=316.49, y=76.00, z=248.69], wi['Pig'/96, l='MpServer', x=316.50, y=74.00, z=287.32], zi['Zombie'/97, l='MpServer', x=310.35, y=75.00, z=289.35], wi['Pig'/105, l='MpServer', x=327.68, y=63.00, z=212.45], zd['Skeleton'/106, l='MpServer', x=320.50, y=21.00, z=235.50], zg['Spider'/107, l='MpServer', x=327.50, y=18.00, z=232.50], wi['Pig'/108, l='MpServer', x=320.75, y=73.00, z=240.50], zi['Zombie'/109, l='MpServer', x=320.48, y=49.00, z=259.18], yp['Creeper'/110, l='MpServer', x=322.23, y=78.00, z=271.85], zd['Skeleton'/111, l='MpServer', x=331.13, y=76.00, z=275.45], zd['Skeleton'/112, l='MpServer', x=320.73, y=78.00, z=279.50], yp['Creeper'/113, l='MpServer', x=324.50, y=24.00, z=301.50], wi['Pig'/114, l='MpServer', x=324.49, y=70.00, z=299.26], wi['Pig'/115, l='MpServer', x=322.56, y=72.00, z=305.55], wi['Pig'/116, l='MpServer', x=335.33, y=71.00, z=299.48], zd['Skeleton'/117, l='MpServer', x=320.51, y=71.00, z=292.74], yp['Creeper'/118, l='MpServer', x=324.50, y=70.00, z=333.50], wi['Pig'/121, l='MpServer', x=342.21, y=63.00, z=194.77], zg['Spider'/122, l='MpServer', x=339.50, y=63.00, z=207.50], yp['Creeper'/123, l='MpServer', x=345.50, y=58.00, z=207.50], wi['Pig'/124, l='MpServer', x=351.36, y=63.00, z=224.03], wi['Pig'/125, l='MpServer', x=343.44, y=63.00, z=218.07], wi['Pig'/126, l='MpServer', x=343.49, y=63.00, z=219.03], wi['Pig'/127, l='MpServer', x=338.23, y=63.00, z=218.35], wi['Pig'/128, l='MpServer', x=336.75, y=63.00, z=215.51], yp['Creeper'/129, l='MpServer', x=338.50, y=63.00, z=208.50], zd['Skeleton'/130, l='MpServer', x=345.50, y=58.00, z=209.50], zi['Zombie'/131, l='MpServer', x=344.50, y=18.00, z=236.50], wi['Pig'/132, l='MpServer', x=342.60, y=64.00, z=227.71], wi['Pig'/133, l='MpServer', x=340.22, y=64.00, z=227.22], wd['Chicken'/134, l='MpServer', x=344.21, y=74.00, z=286.86], wi['Pig'/135, l='MpServer', x=330.69, y=76.00, z=276.40], wi['Pig'/136, l='MpServer', x=348.50, y=64.00, z=284.55], yp['Creeper'/137, l='MpServer', x=348.50, y=65.00, z=280.50], zg['Spider'/138, l='MpServer', x=336.94, y=75.00, z=274.09], wd['Chicken'/139, l='MpServer', x=341.50, y=72.00, z=297.78], wd['Chicken'/140, l='MpServer', x=346.51, y=74.00, z=299.84], yk['item.item.egg'/141, l='MpServer', x=341.07, y=72.00, z=297.99], yk['item.item.egg'/142, l='MpServer', x=346.01, y=74.00, z=299.63], wd['Chicken'/143, l='MpServer', x=339.55, y=71.00, z=307.68], wi['Pig'/144, l='MpServer', x=337.21, y=68.00, z=311.67], yk['item.item.egg'/145, l='MpServer', x=345.01, y=73.00, z=304.53], zd['Skeleton'/146, l='MpServer', x=337.50, y=71.00, z=304.50], wa['Bat'/147, l='MpServer', x=348.44, y=51.64, z=322.50], wi['Pig'/153, l='MpServer', x=343.73, y=63.00, z=192.55], zg['Spider'/154, l='MpServer', x=361.50, y=66.00, z=201.50], zg['Spider'/155, l='MpServer', x=366.50, y=63.00, z=238.50], wi['Pig'/156, l='MpServer', x=361.80, y=62.10, z=267.17], wd['Chicken'/157, l='MpServer', x=362.30, y=73.00, z=287.54], wi['Pig'/158, l='MpServer', x=365.32, y=68.00, z=278.49], wi['Pig'/159, l='MpServer', x=358.35, y=66.00, z=276.25], wd['Chicken'/160, l='MpServer', x=359.13, y=73.00, z=284.62], wd['Chicken'/161, l='MpServer', x=375.13, y=68.00, z=284.50], yk['item.item.egg'/162, l='MpServer', x=363.00, y=73.00, z=286.67], yp['Creeper'/163, l='MpServer', x=366.51, y=68.00, z=279.38], yp['Creeper'/164, l='MpServer', x=362.50, y=75.00, z=298.50], zi['Zombie'/165, l='MpServer', x=354.50, y=67.00, z=313.50], wi['Pig'/166, l='MpServer', x=367.36, y=64.00, z=326.74], zg['Spider'/168, l='MpServer', x=363.80, y=17.00, z=336.20], zd['Skeleton'/169, l='MpServer', x=358.50, y=54.00, z=337.50], wi['Pig'/172, l='MpServer', x=366.26, y=64.00, z=337.46], wa['Bat'/176, l='MpServer', x=378.00, y=18.90, z=193.73], wi['Pig'/177, l='MpServer', x=370.24, y=63.00, z=230.69], wd['Chicken'/178, l='MpServer', x=373.90, y=65.00, z=274.34], wl['Sheep'/180, l='MpServer', x=376.26, y=63.00, z=316.45], wi['Pig'/181, l='MpServer', x=381.42, y=63.00, z=328.70], wa['Bat'/182, l='MpServer', x=375.19, y=57.37, z=330.25], wl['Sheep'/188, l='MpServer', x=382.50, y=57.00, z=337.50], bnn['ljw1004'/213, l='MpServer', x=303.18, y=64.50, z=258.04]]
    Retry entities: 0 total; []
    Server brand: vanilla
    Server type: Integrated singleplayer server
Stacktrace:
    at bln.a(WorldClient.java:496)
    at bcx.b(Minecraft.java:3318)
    at bcx.a(Minecraft.java:689)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 137520352 bytes (131 MB) / 554930176 bytes (529 MB) up to 2120679424 bytes (2022 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn256M
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    Launched Version: vivecraft-1.10.2-Vivecraft-jrbudda-6r4
    LWJGL: 2.9.4
    OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.5.0 NVIDIA 369.09, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

    Using VBOs: Yes
    Is Modded: Very likely; Jar signature invalidated
    Type: Client (map_client.txt)
    Resource Packs: 
    Current Language: English (US)
    Profiler Position: N/A (disabled)
    CPU: 4x Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
    OptiFine Version: OptiFine_1.10.2_HD_U_C2
    Render Distance Chunks: 20
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: null
    OpenGlVersion: 4.5.0 NVIDIA 369.09
    OpenGlRenderer: GeForce GTX 1070/PCIe/SSE2
    OpenGlVendor: NVIDIA Corporation
    CpuCount: 4
```

**Comment by jrbudda** [comment]
I think I fixed this for 1.11 if not sooner
