### ISSUE TITLE
Failed to load with error message

### ISSUE THREAD

**Issue by mcmonkey4eva** [jrbudda/Vivecraft_110#77]
Hey there. Remember me? :P

I gots meself a vive, and wanted to try this out... unfortunately:
```
java.lang.IllegalStateException: Cannot determine focused state of uncreated window
	at org.lwjgl.opengl.Display.isActive(Display.java:567)
	at bcx.setupRenderConfiguration(Minecraft.java:3966)
	at bcx.av(Minecraft.java:1443)
	at bcx.a(Minecraft.java:660)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by mcmonkey4eva** [comment]
Nevermind; reinstalling minecraft and then vivecraft fixed it.
