### ISSUE TITLE
Endermen cause crashes on Spigot server

### ISSUE THREAD

**Issue by Retrogue1** [jrbudda/Vivecraft_110#94]
Made my own spigot server running VSE. When I join, i can play fine until an enderman spawns somewhere, causing me to disconnect with the message "server closed".

I had the nonvr companion app v10 installed, though the same thing happens when on vanilla. I tried running the server and killing all endermen before joining, which works, until another one spawns. 

Crash log: [crash-2017-05-27_19.51.35-server.txt](https://github.com/jrbudda/Vivecraft_110/files/1033914/crash-2017-05-27_19.51.35-server.txt)
pastbin mirror: https://pastebin.com/Kp8dsvkU

**Comment by jrbudda** [comment]
hmm ok, ill take a look, thanks for the report.

**Comment by jrbudda** [comment]
Try this. Very minor difference between 1.10 and 1.11 minecraft.

[Vivecraft_Spigot_Extensions.zip](https://github.com/jrbudda/Vivecraft_110/files/1033931/Vivecraft_Spigot_Extensions.zip)

**Comment by Retrogue1** [comment]
Thanks for the reply! With that zip everything works perfectly in game now, though there are some bad-looking messages in the console.

Whenever a server is started with an enderman in the world it is loading, it shows this: 
`[21:10:21] [Server thread/INFO]: [Vivecraft] Enabling Vivecraft-Spigot-Extensions v1.10-r1
[21:10:21] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_10_R1.EntityEnderman.di()
[21:10:21] [Server thread/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)
[21:10:21] [Server thread/WARN]: 	at org.vivecraft.VSE.getPrivateMethod(VSE.java:220)
[21:10:21] [Server thread/WARN]: 	at org.vivecraft.entities.CustomPathFinderGoalPlayerWhoLookedAtTarget.<init>(CustomPathFinderGoalPlayerWhoLookedAtTarget.java:34)
[21:10:21] [Server thread/WARN]: 	at org.vivecraft.VSE.EditEntity(VSE.java:273)
[21:10:21] [Server thread/WARN]: 	at org.vivecraft.VSE.CheckAllEntities(VSE.java:241)
[21:10:21] [Server thread/WARN]: 	at org.vivecraft.VSE.onEnable(VSE.java:185)
[21:10:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[21:10:21] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:10:21] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[21:10:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugin(CraftServer.java:373)
[21:10:21] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:323)
[21:10:21] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:412)
[21:10:21] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:377)
[21:10:21] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:332)
[21:10:21] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:271)
[21:10:21] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:535)
[21:10:21] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`

And when an enderman is spawned, it shows this: 
`[21:11:18] [Server thread/INFO]: Retrogue1 issued server command: /summon Enderman
[21:11:18] [Server thread/WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_10_R1.EntityEnderman.di()
[21:11:18] [Server thread/WARN]: 	at java.lang.Class.getDeclaredMethod(Unknown Source)
[21:11:18] [Server thread/WARN]: 	at org.vivecraft.VSE.getPrivateMethod(VSE.java:220)
[21:11:18] [Server thread/WARN]: 	at org.vivecraft.entities.CustomPathFinderGoalPlayerWhoLookedAtTarget.<init>(CustomPathFinderGoalPlayerWhoLookedAtTarget.java:34)
[21:11:18] [Server thread/WARN]: 	at org.vivecraft.VSE.EditEntity(VSE.java:273)
[21:11:18] [Server thread/WARN]: 	at org.vivecraft.VSE.onEvent(VSE.java:233)
[21:11:18] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[21:11:18] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[21:11:18] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[21:11:18] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:280)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.World.addEntity(World.java:977)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.WorldServer.addEntity(WorldServer.java:1079)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.ChunkRegionLoader.spawnEntity(ChunkRegionLoader.java:486)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:475)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.CommandSummon.execute(SourceFile:87)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:102)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:37)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[21:11:18] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[21:11:18] [Server thread/WARN]: 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[21:11:18] [Server thread/WARN]: 	at java.util.concurrent.FutureTask.run(Unknown Source)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668)
[21:11:18] [Server thread/WARN]: 	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567)
[21:11:18] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[21:11:18] [Server thread/INFO]: [Retrogue1: Object successfully summoned]`

Full log: [https://pastebin.com/aER3AMnX](url)

I don't notice anything weird happening in game, so if these are nothing to worry about, then it works fine for me.

Thanks for your help!

**Comment by jrbudda** [comment]
Baby steps, lol. I guess you're literally the only person who's playing 1.10.2 vanilla

**Comment by jrbudda** [comment]
[Vivecraft_Spigot_Extensions 1.10.2v2.5.zip](https://github.com/jrbudda/Vivecraft_110/files/1033949/Vivecraft_Spigot_Extensions.1.10.2v2.5.zip)
for real this time.

**Comment by Retrogue1** [comment]
Yup that did it. No more crashes or errors. Thanks for the help!
